# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMKgZhq9HP9-jKo_dWMAQUKtkPr_zZAZ
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go

st.set_page_config(page_title="ECG Distance Comparison", layout="wide")

st.title("Interactive ECG Signal Comparison")

files = {
    "13 cm": "ECG_13.csv",
    "8 cm": "ECG_8.csv",
    "5 cm": "ECG_5.csv",
    "3 cm": "ECG_3.csv"
}

start_time = st.sidebar.number_input(
    "Start time in seconds",
    min_value=0,
    value=5
)

end_time = st.sidebar.number_input(
    "End time in seconds",
    min_value=start_time + 1,
    value=15
)

fig = go.Figure()

for label, file in files.items():
    df = pd.read_csv(file)

    df["PC_Timestamp"] = pd.to_datetime(df["PC_Timestamp"])

    df["Time_sec"] = (
        df["PC_Timestamp"] - df["PC_Timestamp"].iloc[0]
    ).dt.total_seconds()

    df_plot = df[
        (df["Time_sec"] >= start_time) &
        (df["Time_sec"] <= end_time)
    ]

    fig.add_trace(
        go.Scatter(
            x=df_plot["Time_sec"],
            y=df_plot["ECG"],
            mode="lines",
            name=label
        )
    )

fig.update_layout(
    title="ECG Signals at Different Electrode Distances",
    xaxis_title="Time (seconds)",
    yaxis_title="ECG Amplitude",
    hovermode="x unified",
    height=700
)

st.plotly_chart(fig, use_container_width=True)